### PR TITLE
feat: follow neotest-jest changes

### PR DESCRIPTION
**Pull request by shiradofu**
[upstream changes](https://github.com/KaiSpencer/neotest-vitest/compare/a50fe05bece71544851703bf269264390afb3870...haydenmeade:neotest-jest:12138a11525e62011cf0e57aee8a5e7c9f81e08c)

I'm using `assertionResult.location`, which is not currently (2022.07.17) implemented in vitest, would be added before long.
I submitted a small [PR](https://github.com/vitest-dev/vitest/pull/1656).

### CODE REVIEW

**Review by KaiSpencer — APPROVED** [review]
Apologies for the delay on this, missed the notification!
Looks great, thank you for the contribution

**Comment by shiradofu** [comment]
Thank you for your review!
I made some additional commits and for now merged them into my own fork.
https://github.com/shiradofu/neotest-vitest/pull/3

Can I submit another RP for this?

**Comment by KaiSpencer** [comment]
> 

Absolutely!

**Comment by KaiSpencer** [comment]
@shiradofu Absolutely! It would be great if you could do that

**Pull request merged**
